  aws_region: "us-east-1"

  vpc:
    cidr_block: "10.0.0.0/16"
    name: "cloud-resource-manager-vpc"
  
  subnet:
    cidr_block: "10.0.1.0/24"
    name: "cloud-resource-manager-subnet"
  
  internet_gateway:
    name: "cloud-resource-manager-igw"

  route_table:
    name: "cloud-resource-manager-rt"

  ec2: 
    instance_type: "t3.micro"
    ami_id: "ami-0c02fb55956c7d316" # Amazon Linux 2 AMI (HVM), SSD Volume Type
    key_name: "ec2-practice-key"
    name: "cloud-resource-manager-ec2-instance"

  iam:
    role_name: "cloud-resource-manager-iam-role"
